//username array
const usernames = [
    'Aaran',
    'Aaren',
    'Aarez',
    'Aarman',
    'Aaron',
    'Aaron-James',
    'Aarron',
    'Aaryan',
    'Aaryn',
    'Aayan',
    'Aazaan',
    'Abaan',
    'Abbas',
    'Abdallah',
    'Abdalroof',
    'Abdihakim',
    'Abdirahman',
    'Abdisalam',
    'Abdul',
    'Abdul-Aziz',
    'Abdulbasir',
    'Abdulkadir',
    'Abdulkarem',
    'Smith',
    'Jones',
    'Selore',
    'Heart',
    'Ze',
    'Zechariah',
    'Zeek',
    'Zeeshan',
    'Zeid',
    'Zein',
    'Zen',
    'Zendel',
    'Zenith',
    'Zennon',
    'Zeph',
    'Zerah',
    'Zhen',
    'Zhi',
    'Zhong',
    'Zhuo',
    'Zi',
    'Zidane',
    'Zijie',
    'Zinedine',
    'Zion',
    'Zishan',
    'Ziya',
    'Ziyaan',
    'Zohaib',
    'Zohair',
    'Zoubaeir',
    'Zubair',
    'Zubayr',
    'Zuriel',
    'Xander',
    'Jared',
    'Courtney',
    'Gillian',
    'Clark',
    'Jared',
    'Grace',
    'Kelsey',
    'Tamar',
    'Alex',
    'Mark',
    'Tamar',
    'Farish',
    'Sarah',
    'Nathaniel',
    'Parker',
  ];
//email array
  const emails = [
    'Kylem021199@gmail.com',
    'hdias223@gmail.com',
    'ncciw2313@gmail.com',
    'sjk5689@gmail.com',
    'ddisw532@gmail.com',
    'ndaijn@gmail.com',
    'addscac@gmail.com',
    'cxcvvsvf@gmail.com',
    'adafvcd212@gmail.com',
    'acavcbn@gmail.com',
    'dgegr@gmail.com',
    'qweqwqw@gmail.com',
    'asdacxzc@gmail.com',
    'ajeg@gmail.com',
    'ascxacac@gmail.com',
    'xcfvd@gmail.com',
    'dyewf@gmail.com',
    'wdwsaf@gmail.com',
  ];
  //thoughts array
  const thoughts = [
    'Decision Tracker',
    'Find My Phone',
    'Learn Piano',
    'Starbase Defender',
    'Tower Defense',
    'Monopoly Money Manager',
    'Movie trailers',
    'Hello world',
    'Stupid Social Media App',
    'Notes',
    'Messages',
    'Email',
    'Compass',
    'Firefox',
    'Running app',
    'Cooking app',
    'Poker',
    'Deliveries',
  ];
  //getting random item in the array 
  const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUsername = () =>
`${getRandomArrItem(usernames)}`;


const getRandomEmail = () =>
    `${getRandomArrItem(emails)}`;

const getRandomThought = () =>
    `${getRandomArrItem(thoughts)}`;

module.exports = { getRandomUsername, getRandomEmail, getRandomThought};